version: "3"

services:
  app:
    image: pgsqlhademo/app:0.1
    build:
      context: ./app
      dockerfile: Dockerfile
    hostname: app
    environment:
     - DB_USER=testuser
     - DB_PASSWORD=password
     - DB_HOST=pgpool
     - DB_NAME=testdb
    networks:
      pgsql-ha:
    depends_on:
      - pgpool

  primary:
    image: crunchydata/crunchy-postgres:centos7-10.9-2.4.1
    hostname: primary
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=10
      - TEMP_BUFFERS=9MB
      - MAX_CONNECTIONS=101
      - SHARED_BUFFERS=129MB
      - MAX_WAL_SENDERS=7
      - WORK_MEM=5MB
      - PG_MODE=primary
      - PG_PRIMARY_USER=primaryuser
      - PG_PRIMARY_PASSWORD=password
      - PG_DATABASE=testdb
      - PG_USER=testuser
      - PG_PASSWORD=password
      - PG_ROOT_PASSWORD=password
      - PG_PRIMARY_PORT=5432
    networks:
      pgsql-ha:

  replica:
    image: crunchydata/crunchy-postgres:centos7-10.9-2.4.1
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=10
      - TEMP_BUFFERS=9MB
      - MAX_CONNECTIONS=101
      - SHARED_BUFFERS=129MB
      - MAX_WAL_SENDERS=7
      - WORK_MEM=5MB
      - PG_MODE=replica
      - PG_PRIMARY_HOST=primary
      - PG_PRIMARY_PORT=5432
      - PG_PRIMARY_USER=primaryuser
      - PG_PRIMARY_PASSWORD=password
      - PG_DATABASE=testdb
      - PG_USER=testuser
      - PG_PASSWORD=password
      - PG_ROOT_PASSWORD=password
    networks:
      pgsql-ha:
    depends_on:
      - primary

  pgpool:
    image: crunchydata/crunchy-pgpool:centos7-10.9-2.4.1
    hostname: pgpool
    environment:
      - PG_PRIMARY_SERVICE_NAME=primary
      - PG_REPLICA_SERVICE_NAME=replica
      - PG_USERNAME=testuser
      - PG_PASSWORD=password
      - PG_DATABASE=testdb
    ports:
      - 12003:5432
    networks:
      pgsql-ha:
    depends_on:
      - primary
      - replica

  # admin
  pgadm:                                     
    image: dpage/pgadmin4:4
    container_name: pgadm                    
    environment:                             
      - PGADMIN_DEFAULT_EMAIL=admin@demo.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:                                   
      - "8083:80"
    networks:
      pgsql-ha:

  # monitoring
  collect:
    image: crunchydata/crunchy-collect:centos7-10.9-2.4.1
    hostname: collect
    environment:
      - DATA_SOURCE_NAME=postgresql://testuser:password@pgpool:5432/postgres?sslmode=disable
    networks:
      pgsql-ha:
    depends_on:
      - primary
      - replica

  prometheus:
    image: crunchydata/crunchy-prometheus:centos7-10.9-2.4.1
    hostname: prometheus
    environment:
      - COLLECT_HOST=collect
      - SCRAPE_INTERVAL=5s
      - SCRAPE_TIMEOUT=5s
    ports:
     - 9090:9090
    networks:
      pgsql-ha:
    depends_on:
      - collect

  grafana:
    image: crunchydata/crunchy-grafana:centos7-10.9-2.4.1
    hostname: grafana
    environment:
      - ADMIN_USER=admin
      - ADMIN_PASS=password
      - PROM_HOST=prometheus
      - PROM_PORT=9090
      - CRUNCHY_DEBUG=true
    ports:
     - 3000:3000
    networks:
      pgsql-ha:
    depends_on:
      - collect

networks:
  pgsql-ha:

